# Usage:
# askbend -c askbend.toml

[server]
host = "0.0.0.0"
port = 8081

# Question answering config
[qa]
path = "data/"
database = "askbend"
table = "doc"
# Data source name (DSN) for connecting to your Databend cloud warehouse
# https://docs.databend.com/using-databend-cloud/warehouses/connecting-a-warehouse
dsn = "databend://<sql-user>:<sql-password>@<your-databend-cloud-warehouse>/default"
top = 3

[github]
github_token = "your-github-token"
llm_max_tokens = 100000
# Data source name (DSN) for connecting to your Databend cloud warehouse
# https://docs.databend.com/using-databend-cloud/warehouses/connecting-a-warehouse
dsn = "databend://<sql-user>:<sql-password>@<your-databend-cloud-warehouse>/default"
repos = ["your-github-repo"]

